added balanced m9k assault rifles
CFC-Servers/cfc_entity_stubber pull request #13
Opened 2021-05-27 20:09 UTC by StrawWagen

looking for opinions on how i did this, before I start on the other packs
also changed formatting on the minigun to match new formatting

2021-05-27 20:10 UTC, wrefgtzweve commented
local weapon = cfcEntityStubber.getWeapon( "weapon_class" )

2021-05-27 20:11 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_ak47.lua
> +    local weapon = weapons.GetStored( "m9k_ak47" )
on almost all files, use `local SWEP = cfcEntityStubber.GetStored( "m9k_ak47" )` instead

2021-05-27 20:48 UTC, StrawWagen commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_ak47.lua
> +    local weapon = weapons.GetStored( "m9k_ak47" )
pain

2021-05-31 16:44 UTC, wrefgtzweve commented
Yeah, small thing i just realised you're using `CFC_M9k_Stubber.registerStub` for all the functions, we're not using M9k Stubber anymore thus it's `cfcEntityStubber.registerStub`

2021-05-31 16:58 UTC, wrefgtzweve requested changes
Stub files won't work in their current state and some small style / overlook corrections.

2021-05-31 16:58 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_ak74.lua
> +    SWEP.Spawnable = false
why?

2021-05-31 16:58 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_acr.lua
> +    SWEP.Primary.RPM			    = 825
Styling like this is unnecessary

2021-05-31 16:58 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_acr.lua
> +CFC_M9k_Stubber.registerStub( function()
All these files are using `CFC_M9k_Stubber.registerStub` this wont work.
Use `cfcEntityStubber.registerStub` like shown in the examples.

2021-05-31 17:00 UTC, wrefgtzweve commented on lua/cfc_entity_stubber/m9k/assault_rifles/m9k_ak47.lua
> +    SWEP.Primary.RPM                = 600
Quick note, styling like this increases file size by ~20-30% is it worth it?

2021-08-12 22:29 UTC, closed without merging