Fix missing folder bug
CFC-Servers/cfc_entity_stubber pull request #14
Opened 2021-05-31 16:35 UTC by wrefgtzweve

2021-06-01 18:03 UTC, plally commented on lua/cfc_entity_stubber/main_loader.lua
> +            continue
ew continue

2021-06-02 03:46 UTC, brandonsturgeon requested changes

2021-06-02 03:46 UTC, brandonsturgeon commented on lua/cfc_entity_stubber/main_loader.lua
> +        ProtectedCall( stub() )
```suggestion
        ProtectedCall( stub )
```
`ProtectedCall` takes a function

2021-06-02 03:47 UTC, brandonsturgeon approved these changes

2021-06-02 03:47 UTC, merged